portal/urls.py
from django.urls import include, path

from .views import (
    CalendarView,
    DashboardView,
    ManagePropertyListView,
    PropertyCreateView,
    PropertyDeleteView,
    PropertyUpdateView,
    ScheduleDetailView,
    ScheduleView,
)

app_name = "portal"

portal_patterns = [
    # These are urlpatterns specific to a property
    path("edit/", PropertyUpdateView.as_view(), name="property-update"),
    path("delete/", PropertyDeleteView.as_view(), name="property-delete"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("schedule", ScheduleView.as_view(), name="schedule"),
    path(
        "schedule/rooms/<int:room_id>/",
        ScheduleDetailView.as_view(),
        name="schedule-detail",
    ),
    path("", DashboardView.as_view(), name="dashboard"),
]

urlpatterns = [
    path("mine/", ManagePropertyListView.as_view(), name="manage-property-list"),
    path("create/", PropertyCreateView.as_view(), name="property-create"),
    path("<str:slug>/", include(portal_patterns)),
]

portal/views.py
import logging
from typing import Any

from django.db.models import CharField, F, Func, Value
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .mixins import OwnerPropertyEditMixin, OwnerPropertyMixin

logger = logging.getLogger(__name__)


class ManagePropertyListView(OwnerPropertyMixin, ListView):
    template_name = "portal/manage_property_list.html"
    permission_required = "properties.view_property"


class DashboardView(OwnerPropertyMixin, DetailView):
    template_name = "portal/dashboard.html"
    permission_required = "properties.view_property"


class CalendarView(OwnerPropertyMixin, DetailView):
    template_name = "portal/calendar.html"
    permission_required = "properties.view_property"


class ScheduleView(OwnerPropertyMixin, DetailView):
    """
    List view to show all rooms of the property from where detailed schedule can be linked.
    """

    template_name = "portal/schedule.html"
    permission_required = "properties.view_property"


class ScheduleDetailView(OwnerPropertyMixin, DetailView):
    """
    Show the schedule calendar for one single room.
    """

    template_name = "portal/schedule_detail.html"
    permission_required = "properties.view_property"

    def get_schedule_data(self, room):
        qs = room.occurrences.annotate(
            formatted_date=Func(
                F("for_date"),
                Value("yyyy-MM-dd hh:mm:ss"),
                function="to_char",
                output_field=CharField(),
            )
        )
        qs = qs.values_list("formatted_date", "availability")
        return list(qs)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        qs = self.object.rooms.all()
        room_id = self.kwargs.get("room_id")

        context["room"] = room = get_object_or_404(qs, id=room_id)
        context["rates"] = self.get_schedule_data(room)

        return context


class PropertyCreateView(OwnerPropertyEditMixin, CreateView):
    permission_required = "properties.add_property"
    template_name = "portal/property_create.html"


class PropertyUpdateView(OwnerPropertyEditMixin, UpdateView):
    permission_required = "properties.change_property"
    template_name = "portal/property_update.html"


class PropertyDeleteView(OwnerPropertyMixin, DeleteView):
    permission_required = "properties.delete_property"
    template_name = "portal/property_delete.html"

portal/templates/portal/calendar.html
{% extends "layouts/base-sidebar.html" %}

{% block title %}
  Calendar | {{ property.name }}
{% endblock title %}

{% block breadcrumb %}
  Calendar
{% endblock breadcrumb %}

{% block page_title %}
  {{ property.name }}
{% endblock page_title %}

{% block main %}
  <div class="card card-calendar">
    <div class="card-header">
      <h5>Timeline</h5>
    </div>
    <div class="card-body p-3">
      <div id="timeline"></div>
    </div>
  </div>
  <div class="card card-calendar mt-3">
    <div class="card-header">
      <h5>Gantt</h5>
    </div>
    <div class="card-body p-3">
      <div id="gantt"></div>
    </div>
  </div>
{% endblock main %}

{% block js %}
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
       google.charts.load('current', {
            'packages': ['timeline']
       });
       google.charts.setOnLoadCallback(drawChart);

       function drawChart() {
            var container = document.getElementById('timeline');
            var chart = new google.visualization.Timeline(container);
            var dataTable = new google.visualization.DataTable();

            dataTable.addColumn({
                 type: 'string',
                 id: 'Room'
            });
            dataTable.addColumn({
                 type: 'string',
                 id: 'Name'
            });
            dataTable.addColumn({
                 type: 'date',
                 id: 'Start'
            });
            dataTable.addColumn({
                 type: 'date',
                 id: 'End'
            });
            dataTable.addRows([
                 ['President', 'George Washington', new Date(1789, 3, 30), new Date(1797, 2, 4)],
                 ['President', 'Thomas Jefferson', new Date(1801, 2, 4), new Date(1809, 2, 4)],
                 ['Vice President', 'John Adams', new Date(1789, 3, 21), new Date(1797, 2, 4)],
                 ['Vice President', 'Thomas Jefferson', new Date(1797, 2, 4), new Date(1801, 2, 4)],
                 ['Vice President', 'George Clinton', new Date(1805, 2, 4), new Date(1812, 3, 20)],
                 ['Secretary of State', 'John Jay', new Date(1789, 8, 25), new Date(1790, 2, 22)],
                 ['Secretary of State', 'Edmund Randolph', new Date(1794, 0, 2), new Date(1795, 7, 20)],
                 ['Secretary of State', 'Levi Lincoln', new Date(1801, 2, 5), new Date(1801, 4, 1)],
                 ['Secretary of State', 'James Madison', new Date(1801, 4, 2), new Date(1809, 2, 3)]
            ]);
            var options = {
                 timeline: {
                      colorByRowLabel: true
                 },
                 alternatingRowStyle: false
            };
            chart.draw(dataTable, options);
       }
  </script>
  <script type="text/javascript">
       google.charts.load('current', {
            'packages': ['gantt']
       });
       google.charts.setOnLoadCallback(drawChart);

       function drawChart() {

            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Task ID');
            data.addColumn('string', 'Task Name');
            data.addColumn('string', 'Resource');
            data.addColumn('date', 'Start Date');
            data.addColumn('date', 'End Date');
            data.addColumn('number', 'Duration');
            data.addColumn('number', 'Percent Complete');
            data.addColumn('string', 'Dependencies');

            data.addRows([
                 ['2014Spring', 'Spring 2014', 'spring',
                      new Date(2014, 2, 22), new Date(2014, 5, 20), null, 100, null
                 ],
                 ['2014Summer', 'Summer 2014', 'summer',
                      new Date(2014, 5, 21), new Date(2014, 8, 20), null, 100, null
                 ],
                 ['2014Autumn', 'Autumn 2014', 'autumn',
                      new Date(2014, 8, 21), new Date(2014, 11, 20), null, 100, null
                 ],
                 ['2014Winter', 'Winter 2014', 'winter',
                      new Date(2014, 11, 21), new Date(2015, 2, 21), null, 100, null
                 ],
                 ['2015Spring', 'Spring 2015', 'spring',
                      new Date(2015, 2, 22), new Date(2015, 5, 20), null, 50, null
                 ],
                 ['2015Summer', 'Summer 2015', 'summer',
                      new Date(2015, 5, 21), new Date(2015, 8, 20), null, 0, null
                 ],
                 ['2015Autumn', 'Autumn 2015', 'autumn',
                      new Date(2015, 8, 21), new Date(2015, 11, 20), null, 0, null
                 ],
                 ['2015Winter', 'Winter 2015', 'winter',
                      new Date(2015, 11, 21), new Date(2016, 2, 21), null, 0, null
                 ],
                 ['Football', 'Football Season', 'sports',
                      new Date(2014, 8, 4), new Date(2015, 1, 1), null, 100, null
                 ],
                 ['Baseball', 'Baseball Season', 'sports',
                      new Date(2015, 2, 31), new Date(2015, 9, 20), null, 14, null
                 ],
                 ['Basketball', 'Basketball Season', 'sports',
                      new Date(2014, 9, 28), new Date(2015, 5, 20), null, 86, null
                 ],
                 ['Hockey', 'Hockey Season', 'sports',
                      new Date(2014, 9, 8), new Date(2015, 5, 21), null, 89, null
                 ]
            ]);

            var options = {
                 height: 400,
                 gantt: {
                      trackHeight: 30
                 }
            };

            var chart = new google.visualization.Gantt(document.getElementById('gantt'));

            chart.draw(data, options);
            google.visualization.events.addListener(chart, 'select', (e) => {
                 console.log('you clicked');
            });
       }
  </script>
{% endblock js %}

portal/templates/portal/dashboard.html
{% extends "layouts/base-sidebar.html" %}

{% block title %}
  Dashboard {{ property.name }}
{% endblock title %}

{% block breadcrumb %}
  Dashboard
{% endblock breadcrumb %}

{% block page_title %}
  {{ property.name }}
{% endblock page_title %}

{% block main %}
  <h5>{{ object.name }} - Dashboard</h5>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button>
{% endblock main %}

{% block modal %}
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
            <i class="bi bi-x-lg cursor-pointer" aria-label="Close"></i>
          </button>
        </div>
        <div class="modal-body">
          <h2 class="fs-5">Popover in a modal</h2>
          <p>
            This
            <button class="btn btn-secondary"
                    data-bs-toggle="popover"
                    title="Popover title"
                    data-bs-content="Popover body content is set in this attribute.">button</button>
            triggers a popover on click.
          </p>
          <hr />
          <h2 class="fs-5">Tooltips in a modal</h2>
          <p>
            <a href="#" data-bs-toggle="tooltip" title="Tooltip">This link</a> and <a href="#" data-bs-toggle="tooltip" title="Tooltip">that link</a> have tooltips on hover.
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock modal %}

portal/templates/portal/manage_property_list.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}
  My Properties
{% endblock title %}

{% block content %}
  <div class="container min-vh-100 d-flex flex-column justify-content-center">
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-7">
        <div class="card shadow-lg">
          <div class="card-body px-lg-5 py-lg-5 text-center">
            <div class="info mb-4">
              <div class="icon icon-shape icon-xl rounded-circle bg-gradient-warning shadow text-center py-3 mx-auto">
                <svg class="mt-3"
                     width="40px"
                     height="35px"
                     viewBox="0 0 40 40"
                     version="1.1"
                     xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink">
                  <title>spaceship</title>
                  <g id="Basic-Elements" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g id="Rounded-Icons" transform="translate(-1720.000000, -592.000000)" fill="#FFFFFF" fill-rule="nonzero">
                  <g id="Icons-with-opacity" transform="translate(1716.000000, 291.000000)">
                  <g id="spaceship" transform="translate(4.000000, 301.000000)">
                  <path d="M39.3,0.706666667 C38.9660984,0.370464027 38.5048767,0.192278529 38.0316667,0.216666667 C14.6516667,1.43666667 6.015,22.2633333 5.93166667,22.4733333 C5.68236407,23.0926189 5.82664679,23.8009159 6.29833333,24.2733333 L15.7266667,33.7016667 C16.2013871,34.1756798 16.9140329,34.3188658 17.535,34.065 C17.7433333,33.98 38.4583333,25.2466667 39.7816667,1.97666667 C39.8087196,1.50414529 39.6335979,1.04240574 39.3,0.706666667 Z M25.69,19.0233333 C24.7367525,19.9768687 23.3029475,20.2622391 22.0572426,19.7463614 C20.8115377,19.2304837 19.9992882,18.0149658 19.9992882,16.6666667 C19.9992882,15.3183676 20.8115377,14.1028496 22.0572426,13.5869719 C23.3029475,13.0710943 24.7367525,13.3564646 25.69,14.31 C26.9912731,15.6116662 26.9912731,17.7216672 25.69,19.0233333 L25.69,19.0233333 Z" id="Shape">
                  </path>
                  <path d="M1.855,31.4066667 C3.05106558,30.2024182 4.79973884,29.7296005 6.43969145,30.1670277 C8.07964407,30.6044549 9.36054508,31.8853559 9.7979723,33.5253085 C10.2353995,35.1652612 9.76258177,36.9139344 8.55833333,38.11 C6.70666667,39.9616667 0,40 0,40 C0,40 0,33.2566667 1.855,31.4066667 Z" id="Path">
                  </path>
                  <path d="M17.2616667,3.90166667 C12.4943643,3.07192755 7.62174065,4.61673894 4.20333333,8.04166667 C3.31200265,8.94126033 2.53706177,9.94913142 1.89666667,11.0416667 C1.5109569,11.6966059 1.61721591,12.5295394 2.155,13.0666667 L5.47,16.3833333 C8.55036617,11.4946947 12.5559074,7.25476565 17.2616667,3.90166667 L17.2616667,3.90166667 Z" id="color-2" opacity="0.598539807">
                  </path>
                  <path d="M36.0983333,22.7383333 C36.9280725,27.5056357 35.3832611,32.3782594 31.9583333,35.7966667 C31.0587397,36.6879974 30.0508686,37.4629382 28.9583333,38.1033333 C28.3033941,38.4890431 27.4704606,38.3827841 26.9333333,37.845 L23.6166667,34.53 C28.5053053,31.4496338 32.7452344,27.4440926 36.0983333,22.7383333 L36.0983333,22.7383333 Z" id="color-3" opacity="0.598539807">
                  </path>
                  </g>
                  </g>
                  </g>
                  </g>
                </svg>
              </div>
            </div>
            <div class="text-center text-muted mb-4">
              <h2>My Properties</h2>
            </div>
            <div class="text-center">
              <ul class="list-group">
                {% for property in object_list %}
                  <li class="list-group-item px-5 py-3">
                    <a href="{% url 'portal:dashboard' property.slug %}">{{ property.name }}</a>
                  </li>
                {% empty %}
                  <h5>You have no properties yet.</h5>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="card-footer d-flex justify-content-center">
            <span class="text-muted text-sm">Cant't see your property?<a href="{% url 'pages:contact' %}" class="ms-1 text-primary text-gradient text-bold">Contact us</a>.</span>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

portal/templates/portal/property_create.html
<h1>Create a new property</h1>
<form action="" method="post">
  {% csrf_token %
  {{ form }}
  <button type="submit">Create</button>
</form>

portal/templates/portal/property_delete.html
<h1>Delete property</h1>
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  {{ form }}
  <button type="submit">Delete</button>
</form>

portal/templates/portal/property_update.html
{% extends "layouts/base-sidebar.html" %}

{% block title %}
  Update | {{ property.name }}
{% endblock title %}

{% block breadcrumb %}
  Update
{% endblock breadcrumb %}

{% block page_title %}
  {{ property.name }}
{% endblock page_title %}

{% block main %}
  <h1>Update</h1>
  <div class="card">
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Update</button>
      </form>
    </div>
  </div>
{% endblock main %}

portal/templates/portal/schedule.html
{% extends "layouts/base-sidebar.html" %}

{% block title %}
  Schedule | {{ property.name }}
{% endblock title %}

{% block breadcrumb %}
  Schedule
{% endblock breadcrumb %}

{% block page_title %}
  {{ property.name }}
{% endblock page_title %}

{% block main %}
  <div class="card card-plain mb-4">
    <div class="card-header px-0 d-flex justify-content-between pb-0">
      <h5>
        <a href="{{ property.get_portal_url }}" class="icon-move-left">
          <i class="bi bi-chevron-left me-2" aria-hidden="true">
          </i>
          Dashboard
        </a>
      </h5>
    </div>
    <div class="card-body">
      {% for room in property.rooms.all %}
        <a href="{{ room.get_schedule_url }}">
          <h6>{{ room.name }}</h6>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock main %}

portal/templates/portal/schedule_detail.html
{% extends "layouts/base-sidebar.html" %}

{% block title %}
  Schedule | {{ property.name }}
{% endblock title %}

{% block breadcrumb %}
  Schedule
{% endblock breadcrumb %}

{% block page_title %}
  {{ property.name }}
{% endblock page_title %}

{% block extra_css %}
  <link rel="stylesheet" href="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.css" />
{% endblock extra_css %}

{% block main %}
  <div class="card mb-3">
    <div class="card-header">
      <h5>
        <a href="{% url 'portal:schedule' property.slug %}" class="icon-move-left">
          <i class="bi bi-chevron-left me-2" aria-hidden="true">
          </i>
          {{ room.name }}
        </a>
      </h5>
    </div>
    <div class="card-body p-3">
      <div class="table-responsive">
        <table class="table table-sm table-hover align-items-center align-middle">
          {% with occurrences=room.occurrences.all %}
            <tbody>
              <tr>
                <td>
                  <p class="mb-0">Date</p>
                </td>
                {% for occ in occurrences %}
                  <td>
                    <p class="mb-0">{{ occ.for_date|date:"D d" }}</p>
                  </td>
                {% endfor %}
              </tr>
              <tr>
                <td>
                  <p class="mb-0">Available</p>
                </td>
                {% for occ in occurrences %}
                  <td>
                    <p class="mb-0">{{ occ.availability }}</p>
                  </td>
                {% endfor %}
              </tr>
              <tr>
                <td>
                  <p class="mb-0">Rate</p>
                </td>
                {% for occ in occurrences %}
                  <td>
                    <p class="mb-0">{{ occ.rate }}</p>
                  </td>
                {% endfor %}
              </tr>
            </tbody>
          {% endwith %}
        </table>
      </div>
    </div>
  </div>
  <div class="card mt-3 overflow-y-scroll">
    <div class="card-header">
      <h5>Toast UI Calendar</h5>
    </div>
    <div class="card-body overflow-y-scroll" id="calendar" style="height: 900px;"></div>
    <div class="card-footer" id="clicked-event"></div>
  </div>
{% endblock main %}

{% block js %}
  {{ rates|json_script:"rates" }}
  <script src="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.js"></script>
  <script>
       const Calendar = tui.Calendar;

       // Calendar configuration
       const options = {
            usageStatistics: false,
            useDetailPopup: true,
            defaultView: 'week',
            timezone: {
                 zones: [{
                      timezoneName: 'Europe/London',
                      displayLabel: 'London',
                 }],
            },
            calendars: [{
                 id: 'cal1',
                 name: 'Personal',
                 backgroundColor: '#03bd9e',
            }, {
                 id: 'cal2',
                 name: 'Work',
                 backgroundColor: '#00a9ff',
            }],
       };

       const calendar = new Calendar('#calendar', options);

       // Create all the events
       calendar.createEvents([{
            id: 'event1',
            calendarId: 'cal2',
            title: 'Weekly meeting',
            start: '2023-11-07T09:00:00',
            end: '2023-11-07T10:00:00',
       }, {
            id: 'event2',
            calendarId: 'cal1',
            title: 'Lunch appointment',
            start: '2023-11-08T12:00:00',
            end: '2023-11-08T13:00:00',
       }, {
            id: 'event3',
            calendarId: 'cal2',
            title: 'Vacation',
            start: '2023-11-08',
            end: '2023-11-10',
            isAllday: true,
            category: 'allday',

       }, ]);

       // Event handlers
       calendar.on('clickEvent', (obj) => {
            const el = document.getElementById('clicked-event');
            el.innerText = obj.event.title;
       });
  </script>
{% endblock js %}